### ISSUE TITLE
old way file upload and single file change

### ISSUE THREAD

**Issue by ivarsmednis** [TypiCMS/Files#17]
Hello,
I have 2 questions or maybe feature requests.

1. Is there any functionality left to use 'Typicms 2 style' file uploads with regular upload and filename storing in table row. For larger modules i find for clients to use new system is rather messy, as there are many folders with meaningless names now :). Before i start thinking about custom solution, maybe there is some prebuild way to do it like in TypiCMS 2?

2. Is  there any way to change single file. For example if i link file with id 7 for header image, it was easy to change via Files -> Edit -> header.png in Files module.  Maybe there is some other way to link the file module to some globally used image.

**Comment by ivarsmednis** [comment]
I see there is standard file upload in settings, but it looks like custom / one off solution.

**Comment by sdebacker** [comment]
Hello Ivars,

1: I don't understand what you mean, like in TypiCMS 2, files are stored in a table.
2: On hover, you should have a button to edit a file :


Keep me informed.

Samuel

**Comment by ivarsmednis** [comment]
1. In v2 single file uploads filename was stored in model table, not in Files table. Is there prebuilt way to achieve something like that in v3 or do i have to make custom code for that. 

It was very fast to add several files that i could refer to in the code (for example, list image, product image, product image 2,  and refer to them in view code as $model->listImage, $model->productImage and $model->productImage2)  

2. It seems i can edit alt and description here http://jmp.sh/hdrWrXU, which is nice, but i don't see where i can change file and keep reference to this file ID (i could change file in v2).  The problem is, if i use this file in several pages and news items, i have to go through all of them to change file.

Thanks!
Ivars

**Comment by sdebacker** [comment]
1. OK I see, there is no prebuilt way to achieve this in TypiCMS 3.
2. Yes, I removed this functionality as I didn't found a use case for it.

If you develop solutions for any of these points, I’m ok for a PR.

Thanks for using TypiCMS.

**Comment by ivarsmednis** [comment]
I did a quick hack by adding productImage etc accessors in Products mode for second and third images in default $model->files collection, but that doesn't seem like solid way to do. 

Since i haven't done serious pull requests yet. Should i make fresh TypiCMS install, delete TypiCMS package and clone in that place according repository?

**Comment by sdebacker** [comment]
Yes it's the way I do it. You must fork the repository first.
